FROM    centos
MAINTAINER      chesley1979 "80363639@qq.com"
  
RUN set -ex; \
	/bin/echo 'root:88888888' |chpasswd; \
	/bin/echo -e "LANG=\"en_US.UTF-8\"" >/etc/default/local; \
	yum install -y openssh-server net-tools; \
	ssh-keygen -q -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N ''; \
	ssh-keygen -q -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ''; \
	ssh-keygen -t dsa -f /etc/ssh/ssh_host_ed25519_key  -N '' 
ENTRYPOINT ["/usr/sbin/sshd","-D"]

EXPOSE  22
